services:
  web:
    build:
      context: .
    entrypoint: ["/rails/bin/docker-entrypoint"]
    command: bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - /rails/vendor/bundle
      - /rails/app/assets/builds
    environment:
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      # - postgres
      - redis

  worker:
    build:
      context: .
    entrypoint: ["/rails/bin/docker-entrypoint"]
    command: bash -c "bundle install && bundle exec sidekiq"
    volumes:
      - .:/rails
      - /rails/vendor/bundle
      - /rails/app/assets/builds
    depends_on:
      # - postgres
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1

  # postgres:
  #   image: postgres:14
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "postgres"]
  #     interval: 5s
  #     retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5